In [2]:
import json
# from EMSattempt import unroll_experiment, unroll_parameters_gpt
import itertools
import numpy as np
from stabl.EMS import read_json, unroll_parameters,generateModel



params = read_json("./paramsNew.json")
models = [k for k in params["general"]["models"].keys() if params["general"]["models"][k]]
stablModels = [m for m in models if "stabl" in m]
nonStablModels = [m for m in models if "stabl" not in m]

print(stablModels)
print(nonStablModels)

parmlist =unroll_parameters(params)

AttributeError: type object 'spmatrix' has no attribute '__div__'

In [56]:
parmlist[-1]

{'model': 'stabl_en',
 'varValues': 0.1,
 'lifThresh': 0.2,
 'n_bootstraps': 500,
 'replace': True,
 'artificialTypes': 'knockoff',
 'artificialProportions': 1.0,
 'sampleFractions': 1.0,
 'fdrThreshParams': [0.1, 1.0, 0.01],
 'varType': 'thresh',
 'C': array([ 0.01      ,  0.02154435,  0.04641589,  0.1       ,  0.21544347,
         0.46415888,  1.        ,  2.15443469,  4.64158883, 10.        ]),
 'l1_ratio': array([0.1, 0.3, 0.5, 0.7, 0.9]),
 'varNames': ['C', 'l1_ratio']}

In [55]:
p = parmlist[-1]
[ {b:c for b,c in zip(p["varNames"],a)} for a in itertools.product(*[[p[v]] if ii ==0 else p[v] for ii,v in enumerate(p["varNames"])] )]
# print( [a for a in *[p[v] for v in p["varNames"]]])

[{'C': array([ 0.01      ,  0.02154435,  0.04641589,  0.1       ,  0.21544347,
          0.46415888,  1.        ,  2.15443469,  4.64158883, 10.        ]),
  'l1_ratio': 0.1},
 {'C': array([ 0.01      ,  0.02154435,  0.04641589,  0.1       ,  0.21544347,
          0.46415888,  1.        ,  2.15443469,  4.64158883, 10.        ]),
  'l1_ratio': 0.30000000000000004},
 {'C': array([ 0.01      ,  0.02154435,  0.04641589,  0.1       ,  0.21544347,
          0.46415888,  1.        ,  2.15443469,  4.64158883, 10.        ]),
  'l1_ratio': 0.5},
 {'C': array([ 0.01      ,  0.02154435,  0.04641589,  0.1       ,  0.21544347,
          0.46415888,  1.        ,  2.15443469,  4.64158883, 10.        ]),
  'l1_ratio': 0.7000000000000001},
 {'C': array([ 0.01      ,  0.02154435,  0.04641589,  0.1       ,  0.21544347,
          0.46415888,  1.        ,  2.15443469,  4.64158883, 10.        ]),
  'l1_ratio': 0.9}]

In [28]:
c =  np.array([ 0.01      ,  0.02154435,  0.04641589,  0.1       ,  0.21544347,
          0.46415888,  1.        ,  2.15443469,  4.64158883, 10.        ]),
l1_ratio = np.array([0.1, 0.3, 0.5, 0.7, 0.9])
{ for a,b in itertools.product(c,l1_ratio)}

[(array([ 0.01      ,  0.02154435,  0.04641589,  0.1       ,  0.21544347,
          0.46415888,  1.        ,  2.15443469,  4.64158883, 10.        ]),
  0.1),
 (array([ 0.01      ,  0.02154435,  0.04641589,  0.1       ,  0.21544347,
          0.46415888,  1.        ,  2.15443469,  4.64158883, 10.        ]),
  0.3),
 (array([ 0.01      ,  0.02154435,  0.04641589,  0.1       ,  0.21544347,
          0.46415888,  1.        ,  2.15443469,  4.64158883, 10.        ]),
  0.5),
 (array([ 0.01      ,  0.02154435,  0.04641589,  0.1       ,  0.21544347,
          0.46415888,  1.        ,  2.15443469,  4.64158883, 10.        ]),
  0.7),
 (array([ 0.01      ,  0.02154435,  0.04641589,  0.1       ,  0.21544347,
          0.46415888,  1.        ,  2.15443469,  4.64158883, 10.        ]),
  0.9)]

In [16]:
combins = list(itertools.product(*params["stabl_general"].values()))
[{key: value for key, value in zip(params["stabl_general"].keys(), combo)} for combo in itertools.product(*params["stabl_general"].values())]

[{'n_bootstraps': 500,
  'replace': True,
  'artificialTypes': 'random_permutation',
  'artificialProportions': 1.0,
  'sampleFractions': 0.5,
  'fdrThreshParams': [0.1, 1.0, 0.01]},
 {'n_bootstraps': 500,
  'replace': True,
  'artificialTypes': 'random_permutation',
  'artificialProportions': 1.0,
  'sampleFractions': 1.0,
  'fdrThreshParams': [0.1, 1.0, 0.01]},
 {'n_bootstraps': 500,
  'replace': True,
  'artificialTypes': 'knockoff',
  'artificialProportions': 1.0,
  'sampleFractions': 0.5,
  'fdrThreshParams': [0.1, 1.0, 0.01]},
 {'n_bootstraps': 500,
  'replace': True,
  'artificialTypes': 'knockoff',
  'artificialProportions': 1.0,
  'sampleFractions': 1.0,
  'fdrThreshParams': [0.1, 1.0, 0.01]}]

In [5]:

{**params["preprocessing"]}

{'varValues': [0, 0.01, 0.1], 'lifThresh': [0.2]}